config/routes.rb
Christmas::Application.routes.draw do
  resources :gifts
  
  post 'welcome/pick' => 'welcome#pick'
  get 'welcome/find_who' => 'welcome#find_who'
  get 'welcome/yeah' => 'welcome#yeah'

  root 'welcome#index'

  

end

app/models/gift.rb
#encoding: utf-8
class Gift < ActiveRecord::Base
  # attr_accessible :name, :giving, :who, :is_done
  
  scope :no_done, ->{where.not(is_done: true)}
  
  def self.name_list
    lists = {}
    File.open("#{Rails.root}/config/list.yml") do |f|
      f.each_line do |line|
        arr = line.split(':')
        lists[arr[1].strip] = arr[0].strip
      end
    end
    lists
  end
  
  def self.pick_name(who)
    user = Gift.where(who: who).first
    if user.blank? and Gift.no_done.size > 0
      un_gifts = Gift.no_done.delete_if{|g| g.name == who}.map{|g| g.id}
      index = rand(un_gifts.size)
      gift = Gift.find un_gifts[index]
      if who.present?
        return gift
      else
        return false
      end
    else
      return false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/gifts_controller.rb
#encoding: utf-8
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "Kathy", password: "Christmas"

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
    # @gift = Gift.find params[:id]
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
    # @gift = Gift.find params[:id]
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params.merge(:is_done => false))

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gift }
      else
        format.html { render action: 'new' }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    # @gift = Gift.find params[:id]
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    # @gift = Gift.find params[:id]
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:name, :giving, :talk, :token)
    end
end

app/controllers/welcome_controller.rb
#encoding: utf-8
class WelcomeController < ApplicationController
  def index
    @gift = Gift.new
    @names = Gift.name_list
  end
  
  def pick
    unless params[:who].blank?
      who = params[:who].strip
      @gift = Gift.pick_name(params[:who].strip)
      if @gift
        @gift.who = who
        @gift.is_done = true
        token = Array.new(8){rand(1024).to_s(36)}.join
        @gift.token = token
        @gift.save
        redirect_to welcome_yeah_path(:id => @gift.id, :token => token)
      else
        redirect_to :back, :notice => '请重试一次'
      end
    else
      redirect_to :back, :notice => '请输入你的名字'
    end
  end
  
  def yeah
    if params[:token].present?
      @gift = Gift.find params[:id]
      if @gift.token != params[:token]
        redirect_to root_path, :notice => '偷窥别人的愿望是不可以的哦，亲!'
      end
    else
      redirect_to root_path, :notice => '偷窥别人的愿望是不可以的哦，亲!!'
    end
  end
  
  def find_who
    who = params[:who].strip
    name_arr = Gift.name_list.map{|k,v| v}
    # 名字输入是否正确
    if name_arr.include?(who)
      # 是否还有没被抽中的
      if Gift.no_done.size > 0
        # 是否已抽过
        gift = Gift.where(who: who)
        if gift.blank?
          render json: 1
        else
          render json: 0
        end
      else
        render json: 2
      end
    else
      render json: 3
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    if text.present?
      sanitize text.gsub(" ", '&nbsp;').gsub("\r", '<br/>').gsub("\n", '<br/>'), :tags => %w(br a p)
    end
  end
    
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '国王的愿望' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label '愿望内容' %><br>
    <%= f.text_area :giving, size: "50x6" %>
  </div>
  <div class="field">
    <%= f.label '想对天使说的话' %><br>
    <%= f.text_area :talk, size: "50x6" %>
  </div>
  
  <div class="actions">
    <%= f.submit '确认' %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render 'form' %>

<%= link_to '显示', @gift %> |
<%= link_to '返回', gifts_path %>

app/views/gifts/index.html.erb
<h1>Listing gifts</h1>

<table>
  <thead>
    <tr>
      <th>国王</th>
      <th style='width: 400px'>愿望</th>
      <th>天使</th>
      <th></th>
      <th>对天使说的话</th>
      <th></th>
      <th>编辑</th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= link_to gift.name, gift %></td>
        <td><%= gift.giving %></td>
        <td><%= gift.who %></td>
        <td style='width: 20px'></td>
        <td style='width: 200px'><%= gift.talk %></td>
        <td style='width: 20px'></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>新建一个愿望</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>国王:</strong>
  <%= @gift.name %>
</p>

<p>
  <strong>国王的愿望:</strong><br>
  <%= markdown(@gift.giving) %>
</p>
<p>
  <strong>对天使说的话:</strong><br>
  <%= markdown(@gift.talk) %>
</p>


<p>
  <strong>天使:</strong>
  <%= @gift.who %>
</p>


<%= link_to '返回', gifts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Christmas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body >

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="box">
  
  <% if flash[:notice] %>
    <font size="4" color="red"><%= flash[:notice] %></font><br>
  <% end %>
  
  <h1>你要实现谁的圣诞愿望？</h1>
  请在下面找出您的名字<br>
  
  <div class='name'>
  <% @names.each do |key, value| %>
    <%= value %>
  <% end %>
  <br>
  <br>
  </div>
  <%= form_for @gift, :url => welcome_pick_path do |f| %>
    <div class="field">
      <strong><%= f.label '输入你的名字' %></strong>（在上面找你的名字）<br>
      <%= text_field_tag :who %>
    </div>
    <input type='button' name='commit' id='submit_button' />
  <% end %>
</div>

<style type="text/css">
  body {
    background: #c72727 url("/assets/christm.jpg") top center no-repeat;
  }
  .box{ width:650px; height:420px; margin:135px auto; line-height:24px;}
  .name{ width: 400px;}
  #submit_button{
    width: 192px;
    height: 66px;
    border: 0;
/*    text-indent: 0px;*/
    background-image: url('/assets/button.jpg');
  }
</style>

<script type='text/javascript'>
$('#submit_button').click(function(){
  var name = $('#who').val();
  if (name == null || name == ''){
    alert('请输入你的名字！')
    return false;
  }
  $.ajax({
    type: 'get',
    url: '/welcome/find_who',
    data: {who: name},
    dataType: 'json',
    success: function(data) {
      if (data == 0){
        alert('你已经抽过了！');
        return false;
      }
      if (data == 2){
        alert('已经抽完了！');
        return false;
      }
      if(data == 3){
        alert('请在上面找到你的名字！');
        return false;
      }
      $('.new_gift').submit();
    },
    error: function() {
      alert('请求失败！');
    },
  });
  
});
</script>

app/views/welcome/yeah.html.erb
<div class='box'>
<% if flash[:notice] %>
  <%= flash[:notice] %><br>
<% end %>
<% if @gift.present? %>
  <div class='field'>
    <label><strong>你的国王是:</strong></label>
    <%= @gift.name %>
  </div>
  <div>
    <label><strong>国王的愿望是:</strong></label><br>
    <%= markdown @gift.giving %>
  </div>
  <div>
    <label><strong>国王想对你说:</strong></label><br>
    <%= markdown @gift.talk %>
  </div>

<% end %>

<%= link_to '返回', root_path %>
</div>
<style type="text/css">
  body {
    background: #c72727 url("/assets/christm.jpg") top center no-repeat;
  }
  .box{ width:650px; height:420px; margin:135px auto; line-height:24px;}
</style>